### ISSUE TITLE
remove dep on jquery?

### ISSUE THREAD

**Issue by ngzhian** [ngzhian/whereisit#14]

**Comment by celsopalmeiraneto** [comment]
I think we can leave it. That's my reasoning:
- It's included on the package, so the users don't need to download it every time they use the extension.
- Make the contributor write less, even though we don't have that much code.
- Even though we can't use the ajax tools (that would be a nice reason to keep it), the DOM manipulation and selectors help a lot.

**Comment by ngzhian** [comment]
Yea I agree fully on the dom part. Manual creation of dom is just so
painful. Btw, in the latest commits I changed the Ajax calls to use
jQuery.ajax. Let's leave it in then!
