### ISSUE TITLE
hotkey instead of right click and click

### ISSUE THREAD

**Issue by ngzhian** [ngzhian/whereisit#25]

**Comment by exp0nge** [comment]
Ctrl+Click would be wonderful.

**Comment by ngzhian** [comment]
thanks for your suggestion! what do you think about injecting links onto the page itself so the variable itself is highlighted and you can just click on it to jump to the relevant code

**Comment by exp0nge** [comment]
Yeah, that works too. I mean, it will feel natural to those that use IntelliJ

**Comment by ngzhian** [comment]
Try Ctrl-B too (think that's the hotkey for intellij
